version: '3.1'

services:
  dbmaster:
    build: mysql
    container_name: dbmaster
    volumes:
      - "${PWD}/master:/var/lib/mysql/data"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3307:3306
    networks:
      - dbnet
  dbslave:
    build: mysql
    container_name: dbslave
    volumes:
      - "${PWD}/slave:/var/lib/mysql/data"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3308:3306
    networks:
      - dbnet
networks:
  dbnet: