version: '3.1'

services:
  mysqlmaster:
    build: mysql
    container_name: mysqlmaster
    volumes:
      - "${PWD}/mysql/data/master:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3307:3306
    networks:
      - dbnet
  mysqlslave:
    build: mysql
    container_name: mysqlslave
    volumes:
      - "${PWD}/mysql/data/slave:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3308:3306
    networks:
      - dbnet
networks:
  dbnet: